export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const DELETE_FROM_BASKET = 'DELETE_FROM_BASKET'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const CHOOSE_THE_CURRENCY = 'CHOOSE_THE_CURRENCY'


// export const actionTypes = {
//     DECREASE_QUANTITY : 'DECREASE_QUANTITY',
//     ADD_TO_BASKET : 'ADD_TO_BASKET'
// }